project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: about.qmd
        text: Profil
      - href: pages/articles.qmd
        text: Articles
      - href: pages/projets.qmd
        text: Projets
      - href: pages/tidytuesday.qmd
        text: Tidytuesday
    right:
      - icon: github
        href: https://github.com/fmarchais
      - icon: linkedin
        href: https://www.linkedin.com/in/félix-marchais
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: source

execute:
  eval: false
  echo: true
  comment: false
  warning: false
  message: false

lightbox: true
